version: '3'

tasks:

  build-backend:
    desc: build backend side
    cmds:
      - cd backend && docker build -t self-dev-backend .

  build-frontend:
    desc: build frontend side
    cmds:
      - cd frontend && docker build -t self-dev-frontend .

  up:
    desc: start service
    cmds:
      - docker-compose up -d
    silent: true

  down:
    desc: stop service
    cmds:
      - docker-compose down
    silent: true

  fmt:
    desc: formatting project
    cmds:
      - golangci-lint fmt
    silent: true

  migration:
    desc: create new migration file
    cmds:
      - goose -s create {{.NAME}} sql
    vars:
      NAME: "{{.NAME | default \"migration\"}}"
  
  migrate:
    desc: choose last version of migrations
    cmds:
      - goose up
  
  rollback:
    desc: comeback to previous version of migrations
    cmds:
      - goose down
