name: self-dev

services:
  traefik:
    image: traefik:v3.7
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - self-dev

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    networks:
      - self-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.self-dev-backend.rule=Host(`self-dev.test`) && PathPrefix(`/api`)"
      - "traefik.http.routers.self-dev-backend.entrypoints=web"
      - "traefik.http.services.self-dev-backend.loadbalancer.server.port=8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    networks:
      - self-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.self-dev-frontend.rule=Host(`self-dev.test`)"
      - "traefik.http.routers.self-dev-frontend.entrypoints=web"
      - "traefik.http.services.self-dev-frontend.loadbalancer.server.port=80"

  db:
    image: postgres:18-alpine
    networks:
      - self-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "self-dev:/var/lib/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d self-dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    networks:
      - self-dev

volumes:
  self-dev:
    name: "self-dev-volume"

networks:
  self-dev:
    name: "self-dev-network"
    driver: bridge