name: self-dev

services:
  traefik:
    image: traefik:v3.7
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=admin@self-dev.tech"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=self-dev"
      - "traefik.http.routers.traefik.rule=Host(`traefik.self-dev.tech`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - self-dev


  auth:
    image: casbin/casdoor:latest
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    volumes:
      - "./auth/conf:/conf"
      - "./auth/logs:/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.self-dev.tech`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=le"
      - "traefik.http.services.auth.loadbalancer.server.port=8000"
    networks:
      - self-dev
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:18-alpine
    networks:
      - self-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "postgres-data:/var/lib/postgresql"
      - "./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d self-dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    networks:
      - self-dev
    volumes:
      - "redis-data:/data"

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    restart: unless-stopped
    volumes:
      - .env:/app/.env:ro
    networks:
      - self-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.self-dev.tech`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
      args:
        MODE: ${MODE}
    restart: unless-stopped
    networks:
      - self-dev
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`self-dev.tech`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=le'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'

  migrate:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    volumes:
      - .env:/app/.env:ro
    profiles:
      - tools
    entrypoint:
      - goose
    command:
      - -dir
      - /app/migrations
      - up
      - postgres
      - postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - self-dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
    name: "self-dev-postgres"
  redis-data:
    name: "self-dev-redis"
  letsencrypt:
    name: "self-dev-letsencrypt"

networks:
  self-dev:
    name: "self-dev"
    driver: bridge
